name: Build & Publish Release

on:
  push:
    tags:
      - '*'

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Make gradle executable
        run: chmod +x ./gradlew
      - name: Build release
        run: ./gradlew -PprojectVersion="${{ github.ref_name }}" composeApp:assembleRelease
      - name: Sign app APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: composeApp/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
      - name: Rename artifact
        run: mv ${{steps.sign_app.outputs.signedReleaseFile}} filmix-${{ github.ref_name }}.apk
      - name: Upload release apk
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: filmix-${{ github.ref_name }}.apk

  ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Make gradle executable
        run: chmod +x ./gradlew
      - name: Set Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Build compose framework release
        run: ./gradlew -PprojectVersion="${{ github.ref_name }}" composeApp:linkReleaseFrameworkIosArm64
      - name: Build and archive the iOS app
        run: |
          xcodebuild \
           -project iosApp/iosApp.xcodeproj \
           -scheme iosApp \
           -configuration Release \
           -sdk iphoneos \
           -archivePath build/ios/iosApp.xcarchive \
           clean archive \
           CODE_SIGN_IDENTITY="" \
           CODE_SIGNING_REQUIRED=NO \
           CODE_SIGNING_ALLOWED=NO
      - name: Build IPA
        run: |
           # Create directory for artifacts
           mkdir -p output/Payload
           
           # Create IPA
           cp -r build/ios/iosApp.xcarchive/Products/Applications/*.app ./output/Payload
           cd output
           zip -r iosApp.ipa ./Payload
      - name: Rename artifact
        run: mv output/iosApp.ipa filmix-${{ github.ref_name }}.ipa
      - name: Upload release ipa
        uses: actions/upload-artifact@v4
        with:
          name: ipa
          path: filmix-${{ github.ref_name }}.ipa

  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Make gradle executable
        run: chmod +x ./gradlew
      - name: Build release
        run: ./gradlew -PprojectVersion="${{ github.ref_name }}" composeApp:packageDistributionForCurrentOS
      - name: Upload release deb
        uses: actions/upload-artifact@v4
        with:
          name: deb
          path: composeApp/build/compose/binaries/main/deb/*.deb
      - name: Upload release rpm
        uses: actions/upload-artifact@v4
        with:
          name: rpm
          path: composeApp/build/compose/binaries/main/rpm/*.rpm

  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build release
        run: ./gradlew -PprojectVersion="${{ github.ref_name }}" composeApp:packageDistributionForCurrentOS
      - name: Upload release exe
        uses: actions/upload-artifact@v4
        with:
          name: exe
          path: composeApp/build/compose/binaries/main/exe/*.exe

  release:
    runs-on: ubuntu-latest
    needs:
      - android
      - ios
      - ubuntu
      - windows
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: outputs
          merge-multiple: true
      - name: Rename artifacts to lowercase
        working-directory: ./outputs
        run: for filename in $(ls | grep [A-Z]); do mv -i $filename `echo $filename | tr 'A-Z' 'a-z'`; done
      - name: Display release artifacts
        run: ls -R outputs
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: outputs/*
          token: ${{ secrets.TOKEN }}