name: Build & Publish Release

on:
  push:
    tags:
      - '*'

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Make gradle executable
        run: chmod +x ./gradlew
      - name: Build release
        run: ./gradlew -PprojectVersion="${{ github.ref_name }}" composeApp:assembleRelease
      - name: Sign app APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: composeApp/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
      - name: Rename artifact
        run: mv ${{steps.sign_app.outputs.signedReleaseFile}} filmix-${{ github.ref_name }}.apk
      - name: Upload release apk
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: filmix-${{ github.ref_name }}.apk

  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Make gradle executable
        run: chmod +x ./gradlew
      - name: Build release
        run: ./gradlew -PprojectVersion="${{ github.ref_name }}" composeApp:packageDistributionForCurrentOS
      - name: Upload release deb
        uses: actions/upload-artifact@v4
        with:
          name: deb
          path: composeApp/build/compose/binaries/main/deb/*.deb
      - name: Upload release rpm
        uses: actions/upload-artifact@v4
        with:
          name: rpm
          path: composeApp/build/compose/binaries/main/rpm/*.rpm

  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build release
        run: ./gradlew -PprojectVersion="${{ github.ref_name }}" composeApp:packageDistributionForCurrentOS
      - name: Upload release exe
        uses: actions/upload-artifact@v4
        with:
          name: exe
          path: composeApp/build/compose/binaries/main/exe/*.exe

  release:
    runs-on: ubuntu-latest
    needs:
      - android
      - ubuntu
      - windows
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: outputs
          merge-multiple: true
      - name: Rename artifacts to lowercase
        run: rename 'y/A-Z/a-z/' outputs/*
      - name: Display release artifacts
        run: ls -R outputs
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: outputs/*
          token: ${{ secrets.TOKEN }}